### ISSUE TITLE
Support for TB 78

### ISSUE THREAD

**Issue by DirkNie** [tdulcet/Thunderbird-Send#2]
Hi,
is there a version available for TB V78?

Whould be nice.

TIA
  Dirk

**Comment by tdulcet** [comment]
It supports TB 78 if users manually install it. You can find instructions for that here: https://github.com/timvisee/send/issues/15. Note that Mozilla only supports TB 78 for two more weeks, until [November 2](https://wiki.mozilla.org/Release_Management/Calendar). I would recommend you update to TB 91 if possible.

The reason I did not mark it as supporting TB 78 on ATN was because of two bugs that were not fixed until TB 91, including this major bug:
https://github.com/tdulcet/Thunderbird-Send/blob/ca42ffbd306609096feabc326fa57a2b9532f1a7/README.md#L33
I did not want a bunch of negative reviews and bug reports for an issue that I cannot fix or workaround.
