### ISSUE TITLE
Add Support for Password

### ISSUE THREAD

**Issue by nick-perry14** [tdulcet/Thunderbird-Send#6]
Add support to protect the file using the password built into send.  That way, users can send the link across email while having some sort of known password (potentially shared via a more secure medium)

![image](https://user-images.githubusercontent.com/6935777/189753915-2828d17b-6944-4c1e-ae8e-08952ff2f2b3.png)

Edit: SEEN THIS https://bugzilla.mozilla.org/show_bug.cgi?id=1711446

Closing.

**Comment by tdulcet** [comment]
Thanks for the feature request! I assume you are referring to Bug 1711446 because it is linked on [the README](https://github.com/tdulcet/Thunderbird-Send#contributing). That bug is a feature request to allow FileLink extensions to open a composeAction popup directly in the compose window instead of using a separate standalone window as this add-on does now. I think that would be a big user experience (UX) improvement when setting options for each file, but it does not look like they are going to implement it anytime soon, so it should block adding support for a password. Even better would actually be [Bug 1752114](https://bugzilla.mozilla.org/show_bug.cgi?id=1752114).

Anyway, I have considered adding support for a password, but I did not know if there was any interest the feature and it would require significant changes to the add-on, so it has not been a priority. Feel free to reopen this issue if you still want the feature...

**Comment by tdulcet** [comment]
I added support for a password in https://github.com/tdulcet/Thunderbird-Send/commit/cf4c3700ec7900d09a00728b62950f50fa2468bf and this is now included in the version 2.0 update I just published on ATN. You should automatically get this update within 24 hours or you can force it from the Add-ons manager.
